name: 📃 Docs

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build Docs
        run: pnpm run docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: docs
          publish_dir: ./docs/.vitepress/dist/
          commit_message: Deployment Docs
          github_token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
